import { Store } from '@/types';

export const dummyStore: Store[] = [
  {
    storeId: 'store-0',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 1',
    storeLocation: 'Location 59',
    storeCost: 4944,
    storeSize: '200 sqm',
    storeSales: 6920,
    storeCategory: 'Groceries',
    storeRevenue: 62993,
    manager: 'Manager 27',
    managerContact: '+504-394-5655',
  },
  {
    storeId: 'store-1',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 2',
    storeLocation: 'Location 26',
    storeCost: 4347,
    storeSize: '188 sqm',
    storeSales: 7447,
    storeCategory: 'Electronics',
    storeRevenue: 78695,
    manager: 'Manager 19',
    managerContact: '+188-378-4137',
  },
  {
    storeId: 'store-2',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 3',
    storeLocation: 'Location 64',
    storeCost: 4319,
    storeSize: '93 sqm',
    storeSales: 19335,
    storeCategory: 'Furniture',
    storeRevenue: 56282,
    manager: 'Manager 8',
    managerContact: '+880-652-7637',
  },
  {
    storeId: 'store-3',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 4',
    storeLocation: 'Location 16',
    storeCost: 3867,
    storeSize: '143 sqm',
    storeSales: 11284,
    storeCategory: 'Furniture',
    storeRevenue: 22759,
    manager: 'Manager 44',
    managerContact: '+326-166-4546',
  },
  {
    storeId: 'store-4',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 5',
    storeLocation: 'Location 78',
    storeCost: 2445,
    storeSize: '121 sqm',
    storeSales: 6807,
    storeCategory: 'Clothing',
    storeRevenue: 42524,
    manager: 'Manager 34',
    managerContact: '+154-328-9880',
  },
  {
    storeId: 'store-5',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 6',
    storeLocation: 'Location 2',
    storeCost: 4574,
    storeSize: '94 sqm',
    storeSales: 13915,
    storeCategory: 'Groceries',
    storeRevenue: 88219,
    manager: 'Manager 43',
    managerContact: '+986-273-4289',
  },
  {
    storeId: 'store-6',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 7',
    storeLocation: 'Location 62',
    storeCost: 1581,
    storeSize: '96 sqm',
    storeSales: 10881,
    storeCategory: 'Electronics',
    storeRevenue: 89774,
    manager: 'Manager 3',
    managerContact: '+728-125-9291',
  },
  {
    storeId: 'store-7',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 8',
    storeLocation: 'Location 61',
    storeCost: 3821,
    storeSize: '103 sqm',
    storeSales: 14512,
    storeCategory: 'Furniture',
    storeRevenue: 96218,
    manager: 'Manager 23',
    managerContact: '+338-156-2969',
  },
  {
    storeId: 'store-8',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 9',
    storeLocation: 'Location 34',
    storeCost: 2446,
    storeSize: '33 sqm',
    storeSales: 17665,
    storeCategory: 'Electronics',
    storeRevenue: 72480,
    manager: 'Manager 29',
    managerContact: '+409-767-1445',
  },
  {
    storeId: 'store-9',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 10',
    storeLocation: 'Location 66',
    storeCost: 2809,
    storeSize: '184 sqm',
    storeSales: 9284,
    storeCategory: 'Electronics',
    storeRevenue: 20522,
    manager: 'Manager 32',
    managerContact: '+647-964-8680',
  },
  {
    storeId: 'store-10',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 11',
    storeLocation: 'Location 65',
    storeCost: 4785,
    storeSize: '152 sqm',
    storeSales: 12045,
    storeCategory: 'Electronics',
    storeRevenue: 58208,
    manager: 'Manager 28',
    managerContact: '+794-997-7938',
  },
  {
    storeId: 'store-11',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 12',
    storeLocation: 'Location 46',
    storeCost: 2342,
    storeSize: '35 sqm',
    storeSales: 5256,
    storeCategory: 'Electronics',
    storeRevenue: 80470,
    manager: 'Manager 45',
    managerContact: '+471-209-9808',
  },
  {
    storeId: 'store-12',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 13',
    storeLocation: 'Location 37',
    storeCost: 3131,
    storeSize: '51 sqm',
    storeSales: 16124,
    storeCategory: 'Furniture',
    storeRevenue: 46709,
    manager: 'Manager 32',
    managerContact: '+918-478-9896',
  },
  {
    storeId: 'store-13',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 14',
    storeLocation: 'Location 67',
    storeCost: 2583,
    storeSize: '195 sqm',
    storeSales: 7678,
    storeCategory: 'Furniture',
    storeRevenue: 23599,
    manager: 'Manager 10',
    managerContact: '+164-139-8635',
  },
  {
    storeId: 'store-14',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 15',
    storeLocation: 'Location 9',
    storeCost: 4239,
    storeSize: '116 sqm',
    storeSales: 10274,
    storeCategory: 'Groceries',
    storeRevenue: 57838,
    manager: 'Manager 7',
    managerContact: '+715-991-8492',
  },
  {
    storeId: 'store-15',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 16',
    storeLocation: 'Location 71',
    storeCost: 3618,
    storeSize: '35 sqm',
    storeSales: 6835,
    storeCategory: 'Clothing',
    storeRevenue: 37482,
    manager: 'Manager 46',
    managerContact: '+737-939-4234',
  },
  {
    storeId: 'store-16',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 17',
    storeLocation: 'Location 5',
    storeCost: 1643,
    storeSize: '145 sqm',
    storeSales: 13934,
    storeCategory: 'Furniture',
    storeRevenue: 41758,
    manager: 'Manager 37',
    managerContact: '+821-256-2149',
  },
  {
    storeId: 'store-17',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 18',
    storeLocation: 'Location 67',
    storeCost: 1184,
    storeSize: '46 sqm',
    storeSales: 16974,
    storeCategory: 'Electronics',
    storeRevenue: 33736,
    manager: 'Manager 22',
    managerContact: '+706-100-7284',
  },
  {
    storeId: 'store-18',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 19',
    storeLocation: 'Location 52',
    storeCost: 3213,
    storeSize: '78 sqm',
    storeSales: 12570,
    storeCategory: 'Furniture',
    storeRevenue: 86767,
    manager: 'Manager 36',
    managerContact: '+589-446-6406',
  },
  {
    storeId: 'store-19',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 20',
    storeLocation: 'Location 3',
    storeCost: 3006,
    storeSize: '122 sqm',
    storeSales: 13354,
    storeCategory: 'Clothing',
    storeRevenue: 75124,
    manager: 'Manager 11',
    managerContact: '+185-596-8712',
  },
  {
    storeId: 'store-20',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 21',
    storeLocation: 'Location 73',
    storeCost: 4298,
    storeSize: '150 sqm',
    storeSales: 19105,
    storeCategory: 'Furniture',
    storeRevenue: 96775,
    manager: 'Manager 47',
    managerContact: '+522-524-7529',
  },
  {
    storeId: 'store-21',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 22',
    storeLocation: 'Location 62',
    storeCost: 3010,
    storeSize: '31 sqm',
    storeSales: 17693,
    storeCategory: 'Clothing',
    storeRevenue: 86160,
    manager: 'Manager 26',
    managerContact: '+538-499-5037',
  },
  {
    storeId: 'store-22',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 23',
    storeLocation: 'Location 25',
    storeCost: 1819,
    storeSize: '152 sqm',
    storeSales: 14847,
    storeCategory: 'Groceries',
    storeRevenue: 85398,
    manager: 'Manager 40',
    managerContact: '+285-645-7628',
  },
  {
    storeId: 'store-23',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 24',
    storeLocation: 'Location 49',
    storeCost: 1574,
    storeSize: '108 sqm',
    storeSales: 12578,
    storeCategory: 'Electronics',
    storeRevenue: 84175,
    manager: 'Manager 37',
    managerContact: '+375-413-4740',
  },
  {
    storeId: 'store-24',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 25',
    storeLocation: 'Location 31',
    storeCost: 4672,
    storeSize: '122 sqm',
    storeSales: 7034,
    storeCategory: 'Groceries',
    storeRevenue: 21668,
    manager: 'Manager 33',
    managerContact: '+674-619-5191',
  },
  {
    storeId: 'store-25',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 26',
    storeLocation: 'Location 98',
    storeCost: 2202,
    storeSize: '20 sqm',
    storeSales: 14616,
    storeCategory: 'Clothing',
    storeRevenue: 74190,
    manager: 'Manager 14',
    managerContact: '+808-599-6673',
  },
  {
    storeId: 'store-26',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 27',
    storeLocation: 'Location 9',
    storeCost: 2435,
    storeSize: '193 sqm',
    storeSales: 19602,
    storeCategory: 'Electronics',
    storeRevenue: 29977,
    manager: 'Manager 47',
    managerContact: '+453-872-1616',
  },
  {
    storeId: 'store-27',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 28',
    storeLocation: 'Location 43',
    storeCost: 2054,
    storeSize: '25 sqm',
    storeSales: 19848,
    storeCategory: 'Clothing',
    storeRevenue: 30430,
    manager: 'Manager 33',
    managerContact: '+589-989-1254',
  },
  {
    storeId: 'store-28',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 29',
    storeLocation: 'Location 33',
    storeCost: 3239,
    storeSize: '32 sqm',
    storeSales: 14829,
    storeCategory: 'Furniture',
    storeRevenue: 24372,
    manager: 'Manager 40',
    managerContact: '+104-959-7195',
  },
  {
    storeId: 'store-29',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 30',
    storeLocation: 'Location 49',
    storeCost: 1696,
    storeSize: '30 sqm',
    storeSales: 12064,
    storeCategory: 'Clothing',
    storeRevenue: 94325,
    manager: 'Manager 44',
    managerContact: '+599-854-9137',
  },
  {
    storeId: 'store-30',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 31',
    storeLocation: 'Location 43',
    storeCost: 2482,
    storeSize: '129 sqm',
    storeSales: 17990,
    storeCategory: 'Furniture',
    storeRevenue: 40855,
    manager: 'Manager 49',
    managerContact: '+522-237-1839',
  },
  {
    storeId: 'store-31',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 32',
    storeLocation: 'Location 25',
    storeCost: 4707,
    storeSize: '77 sqm',
    storeSales: 17553,
    storeCategory: 'Furniture',
    storeRevenue: 76499,
    manager: 'Manager 48',
    managerContact: '+984-616-6610',
  },
  {
    storeId: 'store-32',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 33',
    storeLocation: 'Location 66',
    storeCost: 2213,
    storeSize: '109 sqm',
    storeSales: 16410,
    storeCategory: 'Electronics',
    storeRevenue: 30861,
    manager: 'Manager 3',
    managerContact: '+834-610-7483',
  },
  {
    storeId: 'store-33',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 34',
    storeLocation: 'Location 43',
    storeCost: 1881,
    storeSize: '111 sqm',
    storeSales: 16301,
    storeCategory: 'Groceries',
    storeRevenue: 93972,
    manager: 'Manager 11',
    managerContact: '+671-988-2568',
  },
  {
    storeId: 'store-34',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 35',
    storeLocation: 'Location 23',
    storeCost: 2431,
    storeSize: '65 sqm',
    storeSales: 8677,
    storeCategory: 'Groceries',
    storeRevenue: 71451,
    manager: 'Manager 4',
    managerContact: '+566-596-6895',
  },
  {
    storeId: 'store-35',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 36',
    storeLocation: 'Location 76',
    storeCost: 4123,
    storeSize: '184 sqm',
    storeSales: 12439,
    storeCategory: 'Furniture',
    storeRevenue: 97256,
    manager: 'Manager 23',
    managerContact: '+481-872-3621',
  },
  {
    storeId: 'store-36',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 37',
    storeLocation: 'Location 61',
    storeCost: 2045,
    storeSize: '193 sqm',
    storeSales: 8398,
    storeCategory: 'Groceries',
    storeRevenue: 23397,
    manager: 'Manager 30',
    managerContact: '+331-430-7270',
  },
  {
    storeId: 'store-37',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 38',
    storeLocation: 'Location 23',
    storeCost: 4319,
    storeSize: '162 sqm',
    storeSales: 17718,
    storeCategory: 'Electronics',
    storeRevenue: 92349,
    manager: 'Manager 27',
    managerContact: '+670-780-8169',
  },
  {
    storeId: 'store-38',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 39',
    storeLocation: 'Location 62',
    storeCost: 1931,
    storeSize: '125 sqm',
    storeSales: 17573,
    storeCategory: 'Electronics',
    storeRevenue: 54445,
    manager: 'Manager 8',
    managerContact: '+179-325-2749',
  },
  {
    storeId: 'store-39',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 40',
    storeLocation: 'Location 97',
    storeCost: 3184,
    storeSize: '145 sqm',
    storeSales: 10667,
    storeCategory: 'Furniture',
    storeRevenue: 71517,
    manager: 'Manager 43',
    managerContact: '+916-663-3461',
  },
  {
    storeId: 'store-40',
    storeImgSrcArr: ['https://source.unsplash.com/random'],
    storeName: 'Store 41',
    storeLocation: 'Location 70',
    storeCost: 1246,
    storeSize: '109 sqm',
    storeSales: 6103,
    storeCategory: 'Groceries',
    storeRevenue: 94788,
    manager: 'Manager 37',
    managerContact: '+929-715-1362',
  },
  {
    storeId: 'store-41',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 42',
    storeLocation: 'Location 95',
    storeCost: 3470,
    storeSize: '137 sqm',
    storeSales: 5775,
    storeCategory: 'Groceries',
    storeRevenue: 58590,
    manager: 'Manager 45',
    managerContact: '+172-460-8419',
  },
  {
    storeId: 'store-42',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 43',
    storeLocation: 'Location 45',
    storeCost: 2057,
    storeSize: '145 sqm',
    storeSales: 14691,
    storeCategory: 'Furniture',
    storeRevenue: 59163,
    manager: 'Manager 6',
    managerContact: '+551-401-8831',
  },
  {
    storeId: 'store-43',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 44',
    storeLocation: 'Location 11',
    storeCost: 1681,
    storeSize: '162 sqm',
    storeSales: 10818,
    storeCategory: 'Furniture',
    storeRevenue: 76717,
    manager: 'Manager 1',
    managerContact: '+574-385-8959',
  },
  {
    storeId: 'store-44',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 45',
    storeLocation: 'Location 5',
    storeCost: 2424,
    storeSize: '145 sqm',
    storeSales: 7358,
    storeCategory: 'Groceries',
    storeRevenue: 88929,
    manager: 'Manager 6',
    managerContact: '+259-997-2827',
  },
  {
    storeId: 'store-45',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 46',
    storeLocation: 'Location 34',
    storeCost: 3229,
    storeSize: '188 sqm',
    storeSales: 9228,
    storeCategory: 'Furniture',
    storeRevenue: 54763,
    manager: 'Manager 32',
    managerContact: '+929-511-5441',
  },
  {
    storeId: 'store-46',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 47',
    storeLocation: 'Location 17',
    storeCost: 4210,
    storeSize: '35 sqm',
    storeSales: 19707,
    storeCategory: 'Clothing',
    storeRevenue: 31195,
    manager: 'Manager 8',
    managerContact: '+187-579-8771',
  },
  {
    storeId: 'store-47',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 48',
    storeLocation: 'Location 21',
    storeCost: 4740,
    storeSize: '160 sqm',
    storeSales: 11501,
    storeCategory: 'Electronics',
    storeRevenue: 42401,
    manager: 'Manager 15',
    managerContact: '+282-137-7977',
  },
  {
    storeId: 'store-48',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 49',
    storeLocation: 'Location 13',
    storeCost: 3593,
    storeSize: '90 sqm',
    storeSales: 15712,
    storeCategory: 'Clothing',
    storeRevenue: 73185,
    manager: 'Manager 48',
    managerContact: '+515-364-9218',
  },
  {
    storeId: 'store-49',
    storeImgSrcArr: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
    ],
    storeName: 'Store 50',
    storeLocation: 'Location 10',
    storeCost: 2234,
    storeSize: '130 sqm',
    storeSales: 17104,
    storeCategory: 'Clothing',
    storeRevenue: 24602,
    manager: 'Manager 47',
    managerContact: '+326-972-4461',
  },
];
