import React from 'react';
import { Noto_Sans_KR } from 'next/font/google';
import type { Metadata } from 'next';

const notoSansKr = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={notoSansKr.className}>{children}</body>
    </html>
  );
}
