export enum StoreColumnDef {
  ID = 'id',
  STORE_NUMBER = 'storeNumber',
  STORE_STATE = 'storeState',
  STORE_NAME = 'storeName',
  STORE_CATEGORY = 'storeCategory',
  STORE_LOCATION = 'storeLocation',
  SALES_REASON = 'salesReason',
  STORE_COST = 'storeCost',
  STORE_SIZE = 'storeSize',
  STORE_SIZE_M2 = 'storeSizeM2',
  MONTHLY_SALES = 'monthlySales',
  MONTHLY_REVENUE = 'monthlyRevenue',
  MONTHLY_COST = 'monthlyCost',
  PERSONAL_COST = 'personalCost',
  MATERIAL_COST = 'meterialCost',
  RENT_COST = 'rentCost',
  DUES_COST = 'duesCost',
  ETC_COST = 'etcCost',
  DESCRIPTION = 'description',
  MOBILE_DESCRIPTION = 'mobileDescription',
  STORE_TAGS = 'storeTags',
  MANAGER = 'manager',
  MANAGER_CONTACT = 'managerContact',
  CREATED_AT = 'createdAt',
  HAS_IMG = 'hasImg',
}
